// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk914Ae1CSU8xqQiQ0mpO-o6hYrtpymU0',
    appId: '1:886764651952:web:eb9c8719c1481442bc0275',
    messagingSenderId: '886764651952',
    projectId: 'uas-ppb-2019130006',
    authDomain: 'uas-ppb-2019130006.firebaseapp.com',
    databaseURL: 'https://uas-ppb-2019130006-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas-ppb-2019130006.appspot.com',
    measurementId: 'G-R2SK09NL0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY9i13u7-r4LQmYYBBOuVJGKiGzNF5ZNg',
    appId: '1:886764651952:android:85f07042ce5e4282bc0275',
    messagingSenderId: '886764651952',
    projectId: 'uas-ppb-2019130006',
    databaseURL: 'https://uas-ppb-2019130006-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas-ppb-2019130006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgA76I7KDWXMIhlU3wPO8ak8Mz5TXEjt0',
    appId: '1:886764651952:ios:cf55e9a255a43460bc0275',
    messagingSenderId: '886764651952',
    projectId: 'uas-ppb-2019130006',
    databaseURL: 'https://uas-ppb-2019130006-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas-ppb-2019130006.appspot.com',
    iosClientId: '886764651952-vvpliftds9p7866899r0u5sribs8beff.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasppb2019130006',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgA76I7KDWXMIhlU3wPO8ak8Mz5TXEjt0',
    appId: '1:886764651952:ios:cf55e9a255a43460bc0275',
    messagingSenderId: '886764651952',
    projectId: 'uas-ppb-2019130006',
    databaseURL: 'https://uas-ppb-2019130006-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas-ppb-2019130006.appspot.com',
    iosClientId: '886764651952-vvpliftds9p7866899r0u5sribs8beff.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasppb2019130006',
  );
}
